version: "3.9"

services:
  products_service:
    build: ./products_service
    container_name: products_service
    ports:
      - "5001:5001"
    networks:
      - shopnet

  payment_service:
    build: ./payment_service
    container_name: payment_service
    ports:
      - "5002:5002"
    networks:
      - shopnet

  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      PRODUCTS_SERVICE_URL: "http://products_service:5001"
      PAYMENT_SERVICE_URL: "http://payment_service:5002"
    ports:
      - "8000:5000"  # Expose gateway on host: 8000
    depends_on:
      - products_service
      - payment_service
    networks:
      - shopnet

networks:
  shopnet:
    driver: bridge
